### ISSUE TITLE
Move wforce.conf to own directory in /etc

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/weakforced#106]
Currently wforce config file is placed to /etc/ root but it would probably make sense to have an own directory for it.

**Comment by neilcook** [comment]
The only question here is how to handle backwards compatibility with previous releases. We can make new installs create /etc/wforce, but we'll have to look in both places for wforce.conf, starting with /etc/wforce/wforce.conf and then fallback to /etc/wforce.conf I guess. Am I missing anything with that logic?

**Comment by cmouse** [comment]
Or just let the user specify the config file location?

**Comment by neilcook** [comment]
I'm not keen on having users specify the location - leads to support issues as potentially every installation is different. Building from source you can always set the install prefix to anything you want anyway.

**Comment by neilcook** [comment]
Commit 2aece32 fixes this by looking for wforce.conf in SYSCONFIGDIR/wforce first before looking in SYSCONFIGDIR.
