### ISSUE TITLE
Support GeoIP v2 API

### ISSUE THREAD

**Issue by neilcook** [PowerDNS/weakforced#118]
Currently GeoIP support is limited to GeoIP legacy databases.

**Comment by neilcook** [comment]
#120 added City and ISP  Legacy DB support, but still only using the legacy v1 API

**Comment by sshipway** [comment]
Apparently, MaxMind are discontinuing updated for the v1 API -- and the subscribed version is now v2 only for new users.  So support for v2 here is becoming essential, particularly for people outside the US where the community GeoIP v1 is rather inaccurate.

**Comment by neilcook** [comment]
Yes we'll look at adding GeoIP v2 support to the next minor/major release of wforce, depending on which comes first. Community contributions welcome of course! :)

**Comment by neilcook** [comment]
Fixed in PR #192
