### ISSUE TITLE
Q: what is the average latency in a wforced cluster?

### ISSUE THREAD

**Issue by sshipway** [PowerDNS/weakforced#137]
I have a question rather than a bug.
In a 3-node wforced cluster, if a `report` call causes an RRD item to be updated, how long (on average) would it take until this is replicated to all available siblings?
I am getting some unexpected behaviour in updates and need to rule this out.

**Comment by neilcook** [comment]
Database replication happens immediately (well it's passed to a replication thread pool, but assuming they're not busy), and uses UDP. So a couple of milliseconds typically.

**Comment by sshipway** [comment]
Thanks, that's what I'd thought, but I seem to be getting some strange latencies in tests here.  I'll start looking at the network...
