### ISSUE TITLE
expose generic redis API into wforce.conf

### ISSUE THREAD

**Issue by darix** [PowerDNS/weakforced#155]
Use case

redis DB with a Set of allowed countries per login. e.g.:

redis-cli:
```
sadd darix DE
```

from the wforce.conf i could do something like: (pseudo code)

```lua
cur_ct = lookupCountry(lt.remote)
if (redis-call('EXISTS ' .. lt.login) == 1) then
   if (redis-call("SISMEMBER " .. lt.login .. " " .. cur_ct) == 0) then
     -- list present but the current country is not in the list
     return -1, "country blocked", "country blocked", { remoteCountry=cur_ct }
  end
else
-- case for all/no countries (depending on how you interpret no list)
end
```

Or would you prefer people use e.g. [gh:nrk/redis-lua](https://github.com/nrk/redis-lua)

**Comment by neilcook** [comment]
I thought about implementing a C(++) based Lua interface to Redis, but frankly there are plenty of Lua modules that do it. We tend to use nrk/redis-lua as you suggest.

**Comment by darix** [comment]
Ok. Thank you. Just wanted to clarify if this is the preferred solution.
