### ISSUE TITLE
Debugging Lua scripts

### ISSUE THREAD

**Issue by moseleymark** [PowerDNS/weakforced#162]
When my runtime Lua is bad (and it often is), I get an error like:

Exception thrown by a callback function called by Lua

There's no identifying information about where the error occurred. I don't know if it's possible for wforce to capture (or if wforce even has visibility into the underlying exception), but if it is, it'd be extremely helpful if wforce reported the traceback for that exception (or even just the offending line). Or is there an option to enable that somewhere that I've missed?

**Comment by neilcook** [comment]
Which version are you using?

**Comment by moseleymark** [comment]
I'm using the 1.2.1 release

**Comment by neilcook** [comment]
Fixed in master already
