### ISSUE TITLE
Suggestion for twReset

### ISSUE THREAD

**Issue by moseleymark** [PowerDNS/weakforced#177]
There are times when I'd like to reset a key but only for a certain field name. For that case, I'm currently doing a db:twSub( .. , twGet( ... ) )  (i.e. subtracting the current value to get back to 0. Might be useful to have a second arg to twReset that takes the field name to reset.

**Comment by neilcook** [comment]
PR #189

**Comment by neilcook** [comment]
PR #189 merged
