### ISSUE TITLE
Debian Files

### ISSUE THREAD

**Issue by moseleymark** [PowerDNS/weakforced#178]
* The debian/control references a package called libprotobuf-def, but the package is actually libprotobuf-dev
* The debian/postinst file is a little intrusive. It really shouldn't be updating the existing wforce.conf file unless it's creating it (IMO). 
* I updated my debian/postinst's definition of where to put wforce.conf to make it inline with other places that wforce seems to look for wforce.conf: WFORCECONF=/etc/wforce/wforce.conf
* The version in debian/changelog is 0.9 and there's an issue with a newline in it which causes build scripts to abort:
dpkg-buildpackage: warning:     debian/changelog(l2): found end of file where expected first heading
* The debian/changelog file's says 'wforced', where debian/control has 'wforce'. For me at least, I have to fix the name in debian/changelog to 'wforce' to get packaging to work.

**Comment by neilcook** [comment]
The packaging is completely out of date currently, as we currently do all packaging outside of the repo. It will be replaced in the next few weeks with a tested, in-repo, docker-based packaging framework.

**Comment by moseleymark** [comment]
Sounds good
