### ISSUE TITLE
Add allow/report/reset etc. stats to the 5 min stats logging

### ISSUE THREAD

**Issue by neilcook** [PowerDNS/weakforced#183]
Currently:
2017-12-14T14:37:53.571193+00:00 dovauth-ch2g-03o wforce[28622]: stats last 300 secs: WTW_0_1=20194 WTW_1_10=1 WTW_10_100=0 WTW_100_1000=0 WTW_Slow=0 WTR_0_1=20175 WTR_1_10=19 WTR_10_100=0 WTR_100_1000=0 WTR_Slow=0

Proposed - something like:
2017-12-14T14:37:53.571193+00:00 dovauth-ch2g-03o wforce[28622]: stats last 300 secs: WTW_0_1=20194 WTW_1_10=1 WTW_10_100=0 WTW_100_1000=0 WTW_Slow=0 WTR_0_1=20175 WTR_1_10=19 WTR_10_100=0 WTR_100_1000=0 WTR_Slow=0 allow=30293 report=29283 reset=2345

Need to think about whether custom endpoints should be included.

**Comment by neilcook** [comment]
@sshipway wrote:
It would be very useful for the existing stats call to also provide counters for the return codes, not just for the function calls.

IE, as well as counts on number of allow() and report() calls made, also counts on the number of allow() calls split by return code 0, -1, or >0.

Even better would be to have a generic count, so in the Lua code you could use something like
addstat(key) followed by increment(key) in an allow or report function, and then the normal stats() call would also return "counter.key: 1" or similar. I know we could implement this in lua using a database, but it would be slow.

Counters like this could then be fed into your favourite monitoring package (MRTG, Zabbix, Nagio, Cacti...) to obtain graphs of weakforced performance and behaviour.

**Comment by sshipway** [comment]
The new custom stats feature is awesome; great to see this.  However, can we have separate stats counters gathered based on the *return value* from the allow function (denies, tarpits, permits)?  Currently, there is no stat for the number of requests denied due to blacklisting, for example, which is a useful indicator of how well we're doing.  A custom stat in the lua couldn't do this as blacklist is checked before it gets there.

**Comment by neilcook** [comment]
Well the stats() function does count “denies” currently. It just doesn’t split out blacklisted vs a Lua-based deny for example,

Neil

**Comment by neilcook** [comment]
This should give you what you want:
> showCommandStats() 
addBLEntry=6
allow=6
allow_allowed=21
allow_blacklisted=6
allow_denied=5
allow_tarpitted=0
countLogins=0
custom=1
delBLEntry=0
getBL=1
getDBStats=2
incLogins=0
ping=1
report=134
reset=0
resetLogins=0
stats=1

Is now part of PR #189

**Comment by neilcook** [comment]
Fixed in PRs #189 and #191
