### ISSUE TITLE
Add support for ipcipher for logged IP addresses

### ISSUE THREAD

**Issue by neilcook** [PowerDNS/weakforced#188]
ipcipher is described here:
https://powerdns.org/ipcipher/

This feature would be a global configuration option that causes all IP addresses (v4 and v6) to be encrypted using ipcipher before logging. Note that this would be for all "built-in" logging, and 'default' policy logging, but would not prevent people from using the custom logging functions to log unencrypted IP addresses. The encrypted IP address should be easily available for all functions, and/or a Lua function to encrypt the IP address.

A tool should be provided to enable the IP addresses in the (built-in) logs to be decrypted.

**Comment by Shivansh028** [comment]
Yes, I know about doing ldap retrievals per-user in Dovecot; however weakforced is wider than dovecot, and we also call it from AppSuite, Momentum and potentially other applications in the future; plus the use case I'm thinking about is where you might have per-domain limit options, which would be a separate LDAP lookup to the userdb. We have multiple customers who may wish to set per-domain thresholds over all of their mailbox domain at once.

As you said, the caching is the key (though having a native function would make the coding easier), including negative caching, to speed things up. Being able to set a positive and negative lookup cache time, plus cache size (and to extract stats on cache occupancy and hit rate for tuning) would be good.
