### ISSUE TITLE
Add stats counters for return codes and errors (Feature request)

### ISSUE THREAD

**Issue by sshipway** [PowerDNS/weakforced#190]
It would be very useful for the existing stats call to also provide counters for the return codes, not just for the function calls.

IE, as well as counts on number of allow() and report() calls made, also counts on the number of allow() calls split by return code 0, -1, or >0.

Even better would be to have a generic count, so in the Lua code you could use something like 
addstat(key) followed by increment(key) in an allow or report function, and then the normal stats() call would also return "counter.key: 1" or similar.  I know we could implement this in lua using a database, but it would be slow.  

Counters like this could then be fed into your favourite monitoring package (MRTG, Zabbix, Nagio, Cacti...) to obtain graphs of weakforced performance and behaviour.

**Comment by neilcook** [comment]
Added this to #183, so closing this. FYI I'm already working on a feature branch for #183 so it makes sense to combine this. I already had some ideas along these lines.
