### ISSUE TITLE
Query Blacklist for firewall integration

### ISSUE THREAD

**Issue by sshipway** [PowerDNS/weakforced#261]
**Is your feature request related to a problem? Please describe.**
The pfSense firewall (and other firewalls) has a feature where it can blacklist incoming connections based on a list of IP addresses retrieved by a URL.  It would be very helpful for us for incoming blacklisted connections to be able to be dropped at the firewall rather than having to attempt login.

**Describe the solution you'd like**
If Weakforced were able to support a query URL that returns a plain list of IP addresses, one per line, that are valid in the blacklist, then this could be hooked directly into by pfSense.

For example, if we could call a URL such as
  http://weakforced/blacklist?minvalid=300&format=plain
to extract a plain-text list of IP addresses, one per line, that have at least 300s validity remaining in the blacklist (this would be so we could synch every 300s to minimise load).

**Describe alternatives you've considered**
Since the blacklist data are already available on the /command=getBL URL, we have tried using this.  However, this comes in JSON format and needs to be parsed, filtered, reformatted and checked for time remaining, and would require us to create a further CGI script on a webserver to convert, or else a whole plugin for the firewall.  Both solutions seem to be suboptimal.

**Additional context**
The more integrations that are natively supported by weakforced, the more useful it becomes.  Using firewalls to protect against brute-force bad actor IP addresses is desirable, but most firewalls have a very simple set of formats supported (DNSBL or HTTP plain text seem to be the usual).
This should be a relatively simple extension to the existing getBL functionality.
A further extension that would aid compatibility would be to be able to optionally disable authentication for this particular query, as some firewalls do not support this.

**Comment by neilcook** [comment]
So there is the custom endpoint command:

setCustomEndpoint(<name  of  endpoint>,  <boolean>, <custom lua func-
         tion>) - Create a new custom REST endpoint with the given name, which
         when invoked will call the supplied custom lua function.  This allows
         admins to arbitrarily extend the wforce REST API with new  REST  end-
         points.   Admins can create as many custom endpoints as they require.
         Custom endpoints can only be accessed via a POST method, and all  ar-
         guments  as passed as key-value pairs of a top-level "attrs" json ob-
         ject (these will be split into two tables - one for single-valued at-
         trs,  and  the  other for multi-valued attrs - see CustomFuncArgs be-
         low).  If the boolean argument is true, then  all  arguments  to  the
         custom  function  will  be sent to all configured named report sinks.
         Return information is passed with a boolean "success"  and  "r_attrs"
         json object containing return key-value pairs.  See wforce.conf.exam-
         ple for an example.  For example:

                  function custom(args)
                    for k,v in pairs(args.attrs) do
                      infoLog("custom func argument attrs", { key=k, value=v });
                    end
                    -- return consists of a boolean, followed by { key-value pairs }
                    return true, { key=value }
                  end

There are a few limitations with the above:
1) It only supports POST not GET
2) Arguments are passed in the body of the request instead of the URL (because it doesn't support GET)
3) Only json is supported as a return format.

I'd be happy to look at a feature request to support a custom endpoint based on GET if those are blockers, which could also include an ability to return data with Content-Type other than json such as text/plain.

I won't include an option to remove authentication - if you want to do that, then throw an HTTP proxy in front of wforce.

**Comment by sshipway** [comment]
Now that (with 2.x) we have the checkBlacklistIp function to allow us to query blacklist membership this helps, but there is (AFAIK) no way to iterate through the entire blacklist, as you would need to for a getTextBlacklist type command. 

Being able to return data in a different format, including plain text, would certainly help with integrations, as would support for GET format requests.  The firewall hooks I've seen are all using GET and want plain text.

As far as authentication goes, some will support it and some not.  Maybe a future wforce will have multiple authentication credentials and rights, and maybe could use source-IP for authorisation in some cases?  A feature request for another time... But in the meantime, a simple proxy can do that, as you say.

**Comment by neilcook** [comment]
Have a look at #268

**Comment by sshipway** [comment]
Yes, #268 seems to provide the necessary functionality.   With a GET endpoint, combined with the function to list all Blacklist members, it should be simple to make an endpoint that returns all blacklisted IPs as text for consumption by security devices.
Thanks for the new features, now waiting for it to be released...

**Comment by neilcook** [comment]
#268 Merged

**Comment by neilcook** [comment]
This will be in 2.1 BTW, which should be released sometime in the summer
