### ISSUE TITLE
Custom stats go into wrong counter [BUG]

### ISSUE THREAD

**Issue by sshipway** [PowerDNS/weakforced#279]
**Describe the bug**
In our system, we have custom counters for a number of different tests we run, and 3 weakforced hosts with the same ruleset in a load-balanced pool
For the last 5 days, one of these counters on one host has been showing extremely high values (over a hundred per minute), but nothing in the logs indicates that the rule has actually triggered.
After restarting weakforced on the affected host, the counter returned to its normal behaviour (once per hour or less).

It appears that something has been erroneously incrementing this counter.  The service has been running for only a week, and none of the other cluster members are exhibiting this behaviour.

**To Reproduce**
I am unfortunately unable to reproduce this behaviour on demand.

**Expected behavior**
The counter should only have incremented when the lua code told it to.

**Screenshots**
n/a

**OS (please complete the following information):**
 - OS: Centos
 - Version 7

**Additional context**
This is very unusual and as I can't replicate it on demand I expect almost impossible to track down.  However I am logging it here for future reference in case others report similar issues.  Possibly a wild pointer or overflow as caused updates to an incorrect area, or some error in cluster replication.
The behaviour returned to normal after restarting the process, and none of the other cluster members (with identical config files) were affected.  Also, it worked fine up until a sudden change 5 days previously.

**Comment by neilcook** [comment]
Hmm, this is extremely unlikely to be an overflow etc, however the custom counters do use a countmin data structure, which is a probabilistic data structure. It's possible there was a hash collision causing the counts to be incorrectly incremented. I will look into using an integer counter for this in future.

**Comment by neilcook** [comment]
On this topic, I'm currently adding support for prometheus to wforce/trackalert. This will lead to the deprecation of the current stats framework in favour of prometheus. In the next release, both will continue to work, but prometheus will be the preferred method. In a future release, the command=stats function will be removed, as well as the showPerf/Command/CustomStats commands, and wforce/trackalert will stop logging stats at 5 minute intervals.
For the period while both are supported, Lua functions such as addCustomStat and incCustomStat will increment both the original stats framework as well as the new prometheus stats.
Prometheus stats will be available on the /metrics/ endpoint using the existing HTTP server.

**Comment by neilcook** [comment]
Now that 2.4.0 is released, I am closing this bug, as the new prometheus metrics should not have this issue. Feel free to open a new issue if you have any problems with that.
