### ISSUE TITLE
[FEATURE] Ready packages for Ubuntu / Debian / CentOS

### ISSUE THREAD

**Issue by vitalvas** [PowerDNS/weakforced#297]
Is it possible to make a repository with the pre-builded packages, as in powerdns or dovecot?

This will save time and more quickly test and implement new versions.

**Comment by neilcook** [comment]
I will consider this. In the meantime, you know how to build packages using pdns-builder right?

**Comment by vitalvas** [comment]
Yes, I use it now.

**Comment by fraenki** [comment]
Oh yes _please_. :+1:

**Comment by neilcook** [comment]
So having considered this, I'm more in favour of producing an 'official' docker image on Docker Hub than publishing packages for a variety of OSs (see WIP PR #309, which will eventually push a docker images automatically to docker hub as 'powerdns/wforce'). The packages support will still be part of the repo, kept up-to-date and available to be built by anyone who wants them, I just don't have the time or energy to build and host packages myself. Anyone who wants to do so is welcome to of course.

**Comment by vitalvas** [comment]
For me - use docker image fully fit.

**Comment by neilcook** [comment]
docker pull powerdns/wforce:v2.4.0
