### ISSUE TITLE
[FEATURE] Add keepalive packets to redisdb connection

### ISSUE THREAD

**Issue by sshipway** [PowerDNS/weakforced#313]
**Is your feature request related to a problem? Please describe.**
When running redis behind a load balancer (for resiliance) idle connections can occasionally be dropped, and wfd need to reconnect.  In particular, when running in Azure the Azure load balancer silently drops connections without a reset resulting in Weakforced threads hanging as they time out trying to talk to redis.  This then results in all threads being consumed and the service hanging.

**Describe the solution you'd like**
There should be an optional keep-alive packet sent to redis from wforce on a configurable interval, so that any connections via a load balancer can be prevented from idle timeouts

**Describe alternatives you've considered**
There is an option in Azure load balancer to cause a polite shutdown of an idle connection rather than dropping packets.  This is not the default though and can only be set via the API, not via the web interface.  It would be better to have connections remain up and not need to reconnect.

**Additional context**
A separate issue is that the timeout on a redis request seems to be unreasonably long, so that when this problem hits, threads hang for long enough to use up all available threads.

**Comment by neilcook** [comment]
All good feedback, thanks Steve. See #314

**Comment by neilcook** [comment]
This fix will make it into 2.4.0 BTW
