### ISSUE TITLE
built-in blacklist lookup with higher precedence?

### ISSUE THREAD

**Issue by jahlives** [PowerDNS/weakforced#315]
Using weakforce 2.2. on centos7. My wforce.conf code does not behave as it should ;-) I have added a blacklisting for a ip adress and a whitelisting of the ip combined with a certain login (using redis). My code in wforce.conf tests white before black but an allow query for the ip/login combo returns blacklisted. Even if I comment out my own blacklist checks the allow query returns that the combo is blacklisted. So I wonder if there is a built-in blacklist check that takes precedence over my own checks?
If I test the combo on WL via `checkWhitelistIPLogin` it returns that is whitelisted.

**Comment by jahlives** [comment]
note to myself: better read the manpage :-)
Found `disableBuiltinBlacklists()`

**Comment by neilcook** [comment]
👍
