### ISSUE TITLE
some redis blacklists not persistent?

### ISSUE THREAD

**Issue by jahlives** [PowerDNS/weakforced#316]
I have the issue that some of the blacklistings added to redis get lost upon restarting wforce daemon. Seems to me that only listings that my report hook adds disappear. Other listings added by other functions in wforce.conf are still present after service restart.
```
disableBuiltinBlacklists()
blacklistPersistReplicated()
whitelistPersistReplicated()
blacklistPersistDB("127.0.0.1", 6379)
whitelistPersistDB("127.0.0.1", 6379)
```
these are my redis wl/bl related settings in wforce.conf
I have a bash wrapper (wforce-listing) to check wl and bl from weakforce
```bash
$ wforce-listing -a show -t black -i 195.202.206.88
{"r_attrs": {"ip": "195.202.206.88", "status": "blacklisted"}, "success": true}
$ systemctl restart weakforce
$ wforce-listing -a show -t black -i 195.202.206.88
{"r_attrs": {"ip": "195.202.206.88", "status": "not listed"}, "success": false}
```
Any idea why that listing get lost upon restart?

**Comment by neilcook** [comment]
Hmm, don't know just from looking at that. Can you paste your wforce.conf in full? Or an edited version that still exhibits the symptoms?

**Comment by jahlives** [comment]
think my wforce.conf is far too big to be put here ;-) Will try later this evening to get a stipped-down version which still shows the issue

**Comment by jahlives** [comment]
here we go with a very stripped version of wforce.conf
```
webserver("0.0.0.0:8085", "--MYTOTALSECRETPASSWORD")
--SETKEY
controlSocket("127.0.0.1:4005")

addACL("0.0.0.0/0")

disableBuiltinBlacklists()
--disableBuiltinWhitelists()
blacklistPersistReplicated() 
whitelistPersistReplicated() 

setNumLuaStates(8)
setNumWorkerThreads(8)
--setVerboseAllowLog()

local string_find = string.find

blacklistPersistDB("127.0.0.1", 6379)
whitelistPersistDB("127.0.0.1", 6379)
setBlacklistIPRetMsg("Access denied due to potential hacking.")


function twreport(lt)
   if lt.remote:tostring() == '127.0.0.1'
   then
     return 0, "", "", { defaultReturn=1 }
   end
   if checkBlacklistIP(lt.remote) == false then
     blacklistIP(lt.remote, 10800, "auto-black ip listing")
   end
end

setReport(twreport)

function allow(lt)
   if checkBlacklistIP(lt.remote) then
     return -1, "Access denied", "", {access=denied}
   else
     return 0, "Access allowed", "", {access=allowed}
   end
end

setAllow(allow)
```
so my report function blacklists what it get ;-) 
Now running a curl call to add an ip
```bash
$ curl -X POST -H "Content-Type: application/json" --data '{"login":"domain.tld","remote":"195.202.206.88"}' http://127.0.0.1:8085/?command=report -u wforce:--MYTOTALSECRETPASSWORD
{"status":"ok"}
# see if it is listed
$ curl -X POST -H "Content-Type: application/json" --data '{"login":"domain.tld","remote":"195.202.206.88"}' http://127.0.0.1:8085/?command=allow -u wforce:--MYTOTALSECRETPASSWORD
{"msg": "Access denied", "r_attrs": {}, "status": -1}
# stop/start wforce and test again
$ curl -X POST -H "Content-Type: application/json" --data '{"login":"domain.tld","remote":"195.202.206.88"}' http://127.0.0.1:8085/?command=allow -u wforce:--MYTOTALSECRETPASSWORD
{"msg": "Access allowed", "r_attrs": {}, "status": 0}

**Comment by jahlives** [comment]
sorry wrong test setup: wrote to the same redis as the other wforce instance (with the loooong wforce.conf). After moving to a dedicated testbox I found that the wforce.conf above does work and blacklists survive a service restart of wforce.
Does this mean somewhere in my productive wforce.conf I do reset those listings upon service restart? Is any special hook called if wforce is restarted (ex reset)?

**Comment by neilcook** [comment]
So there are no special hooks called upon restart. Also, if you enable black/white persistence, there is no scenario where adding a blacklist entry would not also persist it in the redis DB without you seeing an error in the logs (something like: `addPersistEntry: Error adding 127.0.0.1 to persistent redis BlackWhiteListDB (<error message from redis)`). If you are deleting them on restart, you should see a message in the log that the blacklist was deleted (and again if it's deleted it will always be deleted from Redis).

I don't think this is related, but are you sharing a redis instance between all your instances of wforce, or do you have a dedicated redis instance per wforce? Because the "blacklistPersistReplicated()" and "whitelistPersistReplicated()" commands are only for the latter case. For the former case, since Redis is shared, you don't need to persist the blacklist info again.

**Comment by neilcook** [comment]
To debug this, you could take a look at the redis logs, or even tcpdump the traffic between wforce and redis, to see when the entries are getting deleted from Redis, or even to check that the entries are being created in Redis in the first place.

**Comment by jahlives** [comment]
found it ;-) After removing redis data and start redis from scratch all entries became persistent. Is it possible that after updating to wforce 2.2 it could not write to redis anymore and only loaded old entries from redis, from before update? Though I never had redis related error message in logs

**Comment by neilcook** [comment]
Hmm, weird. The keys did change when I added persistent whitelists, but that shouldn't have affected anything because wforce would only read/write the new key formats
