### ISSUE TITLE
Need more detail on how to implement replfwd

### ISSUE THREAD

**Issue by sshipway** [PowerDNS/weakforced#320]
The new replfwd daemon, which can enable replication of blacklists and counters between clusters, seems a great idea.  However , there is insufficient documentation on how to implement this and how it interfaces with the existing wforced clusters.

Does a replfwd instance have to be part of an existing cluster?  Does it pull as well as push, or only push?  If replicating data (as well as blacklists) are there any restrictions on the definitions on the 2 sides (presumably they need to be identical?)

An example of a complete setup would be helpful to help understand the use.

**Comment by neilcook** [comment]
HI Steve, replfwd isn't part of this repo, so this isn't really the best place to discuss it, I'll send you a separate message.
