### ISSUE TITLE
Unexplained long delay on report() function call [BUG?]

### ISSUE THREAD

**Issue by sshipway** [PowerDNS/weakforced#326]
**Describe the bug**
On rare occasions, a call to the report API will block for tens of seconds, before completing normally. 

**To Reproduce**
This is not reproducible on demand, but it appears to happen
1) When the weakforced service has recently been restarted
2) When the whole cluster has been restarted (IE the working in-memory database is empty)
3) When we run our test scripts (which submit a large number of reports and access calls over a short period of time)

It is noteworthy that the call still responds correctly, but many seconds (e.g. 40s) later.

API call is being made from curl --

    curl -s -X POST -H "Authorization: Basic $AUTH" -H 'Content-Type: application/json' --data "$payload" "http://$ENDPOINT:8084/?command=report"

It does not seem to have any consistency in the passed parameters - it can happen on logging success, failure, etc.

**Expected behavior**
Normal response time -- IE almost immediate

**OS (please complete the following information):**
 - OS: Centos 
 - Version: 7

**Additional context**
It seems that this is more likely to happen in clustered wforce installs though I cannot verify this
It only seems to affect report calls, not access calls
The obvious suspect would be our report() function content, which does make calls to an rbl lookup and to blacklisting as well as logging functions.  However the rbl lookup has a 400ms timeout set and there does not seem to be anything that could potentially cause such a large delay.
I understand this is almost impossible to debug, but am logging it here in case it is helpful

**Comment by neilcook** [comment]
Hi Steve, which version of wforce are you using?

**Comment by sshipway** [comment]
Version 2.4.0

**Comment by neilcook** [comment]
This is interesting. If there was a locking issue, then all the report threads would block, not just one or two. Most of the potential issues I can think of would be the same - affecting all the threads, not just one. Can you send the result of an HTTP query to the /metrics endpoint after this has happened?

**Comment by neilcook** [comment]
Hi Steve, one possibility that I did think of here - are you using an TCP siblings, or are they all UDP? If TCP, this could be a connect timeout issue.

**Comment by sshipway** [comment]
No, we have UDP siblings.
It's not happened again recently, so is difficult to predict.  One possibility is that its being caused by one of the report actions that makes an https POST to a REST service.  This is configured with a 0.5s timeout to prevent excessive blocking but I've seen anecdotal evidence that the lua library https.timeout setting is ignored

**Comment by neilcook** [comment]
Hi Steve, does the call to the HTTP REST service need to parse a response, or is is fire and forget? If the latter, then you could use a custom webhook instead, which won't block the report function at all.

**Comment by sshipway** [comment]
It's a fire-and-forget, but is triggered by a successful login from a specific country in specific situations, so has to come from the report() function.  Ive seen some doc suggesting that even if using https I should still set the timeout on the http module (as one calls the other) so I've done that, and will see if the blocking situation happens again.  
It would maybe be a good idea for report() and allow() to have a user-settable global timeout (maybe default to 100ms) as they are so time-sensitive, as this would prevent this sort of blockage from a badly-behaved function

**Comment by neilcook** [comment]
So if it's fire and forget, the custom webhook approach should work fine, and then you can guarantee it won't affect performance.

I'd have to look into global timeouts, but I doubt it would be easy, because interrupting a pthread running a Lua state will almost certainly have all kinds of side-effects.

**Comment by neilcook** [comment]
Hi Steve, did you get the bottom of this issue? Was it the HTTP lookup timeout?

**Comment by neilcook** [comment]
Hi Steve let me know if this is still a problem, otherwise I'll close the issue if that's ok?

**Comment by sshipway** [comment]
I think close it - the problem has not come back again and may have been dns-related.  Thanks for the help
