### ISSUE TITLE
[FEATURE] Weakforced missing ebuilds for gentoo

### ISSUE THREAD

**Issue by xpunkt** [PowerDNS/weakforced#383]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when gentoo miss ebuilds for good software

**Describe the solution you'd like**
all software from PowerDNS is avail as ebuilds in gentoo, weakforced is just to complicated to do for me

**Describe alternatives you've considered**
learning write them self :)

**Additional context**
maybe common more that gentoo is not lost in the precompiled solutions, i know freebsd is in same boat

**Comment by stintel** [comment]
https://github.com/stintel/gentoo-overlay/commit/aeb3f7881f332752eb50e8b397901be3e5de323f

**Comment by xpunkt** [comment]
thanks for wforced gentoo ebuild, i have it installed now, but it miss /etc/conf.d/wforced so the /etc/init.d/wforced stays in forground waiting for interactive inputs

**Comment by neilcook** [comment]
thanks for this - I know nothing about gentoo ebuilds, so this is really helpful!

**Comment by xpunkt** [comment]
its just /etc/conf.d/wforce without d, and its only need to contain wforce_args="..."

my content

# /etc/conf.d/wforce

# Options to pass on to wforce during the start
wforce_args="--config=/etc/weakforced/wforce.conf --regexes=/etc/weakforced/regexes.yaml --daemon --facility=daemon --loglevel=6"

## Set the maximum number of open file descriptors
# rc_ulimit="-n 16000"

## order of dependice
# rc_before="dovecot"
