### ISSUE TITLE
[BUG] -ltermcap fails on gentoo

### ISSUE THREAD

**Issue by xpunkt** [PowerDNS/weakforced#385]
**Describe the bug**
https://github.com/PowerDNS/weakforced/blob/master/trackalert/Makefile.am#L48

**To Reproduce**
git clone https://github.com/PowerDNS/weakforced.git
cd weakforced
autoreconf -vi
./configure --disable-dns --disable-docker --enable-trackalert
make

**Expected behavior**
trackalart should work

**OS (please complete the following information):**
 - OS: [gentoo]
 - Version [Gentoo Linux 2.9]

**Additional context**
i have not searched deap to find if there is more places to find -ltermcap

**Comment by xpunkt** [comment]
change line 48 from -lreadline -ltermcap to -lreadline then it works

**Comment by neilcook** [comment]
Yes, looks like wforce daemon doesn’t have this, not sure why trackalert still does. Feel free to submit a PR with this change.

**Comment by neilcook** [comment]
See PR #386

**Comment by neilcook** [comment]
Merged in #386
