### ISSUE TITLE
[FEATURE] Split regression so it runs jobs in parallel

### ISSUE THREAD

**Issue by jsoref** [PowerDNS/weakforced#412]
**Is your feature request related to a problem? Please describe.**
The regression workflow takes 90mins to run to completion: https://github.com/PowerDNS/weakforced/actions/runs/7342202732 that's too long.

**Describe the solution you'd like**
There should be units of work that can be done in parallel jobs within the workflow.

Whether that's compiling 3 objects in 3 jobs at the beginning and then passing them around via a cache / artifact, or whether that's just running 3 parallel jobs to handle 3 sections of work, ... there has to be something that doesn't depend on previous steps

**Describe alternatives you've considered**
I could wait the time it takes for the workflows to run.

**Additional context**
https://github.com/PowerDNS/weakforced/actions/runs/7342202732 
![image](https://github.com/PowerDNS/weakforced/assets/2119212/772cd340-5d2a-49cf-afaf-6f0828e37215)

**Comment by neilcook** [comment]
Indeed, the regression runs twice, once for clang and once for g++ so that's a prime candidate for running in parallel.
