### ISSUE TITLE
[FEATURE] Change time to logging stats directive

### ISSUE THREAD

**Issue by bypper** [PowerDNS/weakforced#414]
**Is your feature request related to a problem? Please describe.**
Stats are logged every 5 minutes.
This can be too much, but I can't see any configuration directive for change it.

**Describe the solution you'd like**
I think is necessary an configuration directive for set time to logged stats, and not 5 min.

**Describe alternatives you've considered**
I like this stats, I don't wont remove with Rsyslog features, but 5 min it's too much for me.

**Comment by neilcook** [comment]
The stats logging feature may be removed in a future release - you should really be using the prometheus metrics, which have all the same information, but in a standard format.

**Comment by bypper** [comment]
> The stats logging feature may be removed in a future release - you should really be using the prometheus metrics, which have all the same information, but in a standard format.

Do you have any link with info about this?

**Comment by neilcook** [comment]
The prometheus metrics are part of the wforce API under /metrics:
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/PowerDNS/weakforced/master/docs/swagger/wforce_api.7.yml

See https://prometheus.io for more info about prometheus in general.
