### ISSUE TITLE
[BUG] License conflicts

### ISSUE THREAD

**Issue by P-EB** [PowerDNS/weakforced#416]
**Describe the bug**
Hi,

Some of your code is licensed under GPL-3, other parts (eg [`threadname](https://github.com/PowerDNS/weakforced/blob/master/ext/ext/threadname.cc)) is under GPL-2 (not GPL-2+).

According to [GNU](https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility), this is not possible.

Could you relicense any GPL-2 code under "GPL Version 2 or later" ?

This would allow me to package weakforced into Debian.

Thanks !

**Comment by neilcook** [comment]
Sure, this should be possible

**Comment by neilcook** [comment]
I had a look, and only threadname seems to conflict, everything else already GPL-2+, GPL-3 or a compatible license.

**Comment by P-EB** [comment]
<3

**Comment by P-EB** [comment]
@neilcook Thanks!

Do you have plans on a release I could use for Debian? :)

**Comment by P-EB** [comment]
Could you release something like a patch release (ie 2.10.1.1), potentially just having the license fix over 2.10.1 ? Alternatively I can wait a couple months.

**Comment by neilcook** [comment]
Well it would be 2.10.2 not 2.10.1.1. If you can wait a bit that would be great.

**Comment by P-EB** [comment]
Ack

**Comment by neilcook** [comment]
2.10.2 released

**Comment by neilcook** [comment]
JFYI

**Comment by P-EB** [comment]
Didn't reply but saw the release, thanks! <3
