### ISSUE TITLE
Systemd notify integration broken

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/weakforced#46]
The provided systemd file does not work in debian/jessie because weakforced fails to notify properly.

**Comment by neilcook** [comment]
Hmm, it should do if libsystemd is defined - from wforce.cc(792):

#ifdef HAVE_LIBSYSTEMD
  sd_notify(0, "READY=1");
#endif

Did you install libsystemd-dev?

**Comment by cmouse** [comment]
Probably not, but the systemd unit file should use simple then

**Comment by neilcook** [comment]
Yes it should

**Comment by cmouse** [comment]
Installing libsystemd-dev fixed the problem.

**Comment by neilcook** [comment]
Yeah so I'll make a change so that the "Type" is "simple" if libsystemd-dev wasn't installed.

**Comment by neilcook** [comment]
d0bae52 fixes this issue
